### ISSUE TITLE
The Game Just Randomly Crashes

### ISSUE THREAD

**Issue by AcoYTMC** [Emafire003/LightWithin#17] opened 2024-06-23 22:33 UTC
The Game Just Randomly Crashes

Sometimes i'm just jumping around and it crashes other times i'm just in third person

LightWithin mod version: 1.1.0+1.20.1
Minecraft Version: 1.20.1
Fabric API version: 0.92.2+1.20.1

I wasn't using coloredglowlib
I wasn't using cardinal components API

**Screenshots and files**
[crash-2024-06-23_15.27.42-server.txt](https://github.com/user-attachments/files/15946621/crash-2024-06-23_15.27.42-server.txt)

**Comment by AcoYTMC** [comment] 2024-06-25 03:59
PLEASE OPTIMIZE THIS SOON IT STILL CRASHES WHEN JUMPING

**Comment by Emafire003** [comment] 2024-06-25 08:50
There was a beta out to find problems like these, but they didn't come up. No need to insist like, one day after, I saw the issue, I don't have too much time to work on it. But, I'll look into it and post an update as soon as possible. Thank you. 

Also, can you please describe the issue a little better? Like, when does it happen? Do you play singleplayer or  you have the mod on the server? What light type do you have? What target? Etc.

**Comment by Emafire003** [comment] 2024-06-25 10:55
I'm not sure this is related to the jumping crash thing, so please provied information on that kind of crash as well.

**Comment by AcoYTMC** [comment] 2024-06-25 15:00
I was hosting a server with essential I had wind targetted to myself but it doesn't really have a pattern it only sometimes happens when I jump

**Comment by Emafire003** [comment] 2024-06-25 15:04
So it's the server that crashes? Btw, the test release should probably work then, let me know.

**Comment by AcoYTMC** [comment] 2024-06-25 15:09
I'll see if it works

**Comment by AcoYTMC** [comment] 2024-06-25 15:12
I can also send a list of the mods I have installed if needed

**Comment by AcoYTMC** [comment] 2024-06-25 15:23
It Still Crashes Randomly this time I was just killing a creeper but I landed a crit and it crashed I put a list of mods under the crash report

[crash-2024-06-25_08.17.27-client.txt](https://github.com/user-attachments/files/15973606/crash-2024-06-25_08.17.27-client.txt)

cardinal-components-api-5.2.2
continuity-3.0.0-beta.5+1.20.1
ct-1.0.0
double-jump-attribute-main-1.1.8
essential_1-3-2-7_fabric_1-20-1
fabric-api-0.92.2+1.20.1
IAS-Fabric-1.20.1-9.0.0-beta.5
itemscroller-fabric-1.20.1-0.20.0
lambdynamiclights-2.3.2+1.20.1
lightwithin-1.1.1+1.20.1-dev
litematica-fabric-1.20.1-0.15.3
malilib-fabric-1.20.1-0.16.3
midnightlib-fabric-1.4.1.1
modelfix-1.15-fabric
modmenu-7.2.2
reeses_sodium_options-1.7.2+mc1.20.1-build.101
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.10+mc1.20.1
sound-physics-remastered-fabric-1.20.1-1.4.2
trinkets-3.7.2
voicechat-fabric-1.20.1-2.5.15
YetAnotherConfigLib-3.5.0+1.20.1-fabric

ct-1.0.0 and double-jump-attribute-main-1.1.8 are custom mods I made/edited

**Comment by Emafire003** [comment] 2024-06-25 15:37
This one is related to an entity and continuity, not LightWithin

**Comment by AcoYTMC** [comment] 2024-06-25 15:50
so if i remove continuity it should hopefully not crash?

**Comment by Emafire003** [comment] 2024-06-25 15:56
Most likely

**Comment by tajemniktv** [comment] 2024-07-22 21:41
Oddly my friend also has similiar issue? I don't have full logs, as he only sent this crash report - Not sure about the settings of how it happened, so I'm really sorry I can't provide any more information about this, except that something might be up
```
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at me.emafire003.dev.lightwithin.LightWithin.lambda$registerReadyLightCacheRemover$16(LightWithin.java:617) ~[lightwithin-1.1.2+1.20.1.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cle002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:6862) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Emafire003** [comment] 2024-07-23 10:21
Ah. I will need a bit more context like what light type and target they had, if they were on a server and full logs if possibile. But I may have spotted the issue.

**Comment by Emafire003** [comment] 2024-07-30 09:46
@tajemniktv are you/your friend able to provide the logs? Beacuse I can't really reproduce it seems.

**Comment by tajemniktv** [comment] 2024-07-30 18:15
Oh shoot, so sorry, we ended up removing LightWithin from the modpack in the end... I'm still unsure what exactly happened prior the the server crash sadly, so I am not able to provide more information sadly... 

It *could* be a mod compatibility issue, as it were the early days of the modpack we were cooking. But if noone else seems to be experiencing this anymore, then not sure if it's worth keeping the issue on the tracker open. Really sorry I couldn't be more helpful with this one:x

**Comment by Emafire003** [comment] 2024-07-30 18:20
I've modified the code anyway, using another type of map, and hopefully should be fixed anyway in the next release

**Comment by tajemniktv** [comment] 2024-07-30 18:37
Oh - I will be looking out for the stable release then and ask my friend what he thinks about trying it out again. I remember him saying that it's such a cool mod and he was a bit down we had to remove it, but that's what he decided was the best, as the number of issues happening with the modpack back then, was enormous and I think he wasn't in the mood for debugging lmao

**Closed** 2024-07-31 16:45 UTC
Labels: bug

**Comment by Emafire003** [comment] 2024-07-31 16:47
@tajemniktv Hey, if you want to help https://github.com/Emafire003/LightWithin/releases/tag/v1.1.3-dev try out that version and let me know if the issue keeps happening. (It shouldn't)
